Task dev 3
NastassiaZhylinskaya/TAT_2018 pull request #3
Opened 2018-03-07 18:25 UTC by NastassiaZhylinskaya

2018-03-07 18:31 UTC, IgorKheidorov requested changes

2018-03-07 18:31 UTC, IgorKheidorov commented on DEV-3/DecimalNumberRadixConverter.cs
> +  {
Better LATIN_SYMBOLS_START_POSITION

2018-03-07 18:31 UTC, IgorKheidorov commented on DEV-3/DecimalNumberRadixConverter.cs
> +    /// <summary>
method converts

2018-03-07 18:31 UTC, IgorKheidorov commented on DEV-3/DecimalNumberRadixConverter.cs
> +    /// This method convert decimal number
to other

2018-03-07 18:31 UTC, IgorKheidorov commented on DEV-3/EntryPoint.cs
> +      {
Create local value for Parse(args[1]) not to call the method three times

2018-03-07 18:31 UTC, IgorKheidorov commented on DEV-3/DecimalNumberRadixConverter.cs
> +    public int SourceNumber { get; private set; }
Why not use BigInteger?

2018-03-08 18:39 UTC, AlexanderSoroka approved these changes
Approved due to deadline

2018-03-08 18:39 UTC, AlexanderSoroka commented on DEV-3/DecimalNumberRadixConverter.cs
> +    const int LATIN_SYMBOLS_START_POSITION = 55;
not obvious constant value

2018-03-08 18:39 UTC, AlexanderSoroka commented on DEV-3/DecimalNumberRadixConverter.cs
> +    /// <summary>
add blank line before new method description

2018-03-08 18:39 UTC, AlexanderSoroka commented on DEV-3/EntryPoint.cs
> +      int basisOfANewNumeralSystem = int.Parse(args[1]);
Must be called within try/catch block

2018-03-08 18:39 UTC, AlexanderSoroka commented on DEV-3/DecimalNumberRadixConverter.cs
> +        int asciSymbolFirstPosition = (rest >= 10) ? LATIN_SYMBOLS_START_POSITION : '0';
Strange mix of magic number and constant

2018-03-08 18:39 UTC, AlexanderSoroka commented on DEV-3/DecimalNumberRadixConverter.cs
> +      string convertedNumberString = String.Empty;
just 'result' would be much better

2018-03-15 23:18 UTC, merged